# Generated by Django 4.1 on 2023-07-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
