# Generated by Django 4.1 on 2023-07-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0002_alter_aluno_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
