# Generated by Django 4.2.3 on 2023-08-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0003_aluno_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='d_ra',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='aluno',
            name='ra',
            field=models.CharField(default='', max_length=100),
        ),
    ]
