# Generated by Django 4.2.3 on 2023-10-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0004_aluno_d_ra_aluno_data_nascimento_aluno_ra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(choices=[('CN', 'Certidão de Nascimento'), ('RGA', 'RG - Aluno'), ('CPFA', 'CPF - Aluno'), ('CV', 'Carteira Vacinação'), ('RGR', 'RG - Responsável'), ('CPFR', 'CPF - Responsável'), ('CNH', 'CNH'), ('FM', 'Ficha de Matrícula'), ('CR', 'Comprovante de Residência'), ('LD', 'Laudo'), ('OT', 'Outros')], max_length=4)),
                ('caminho', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='ano',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='aluno',
            name='serie',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.CreateModel(
            name='Telefones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_tipo', models.CharField(choices=[('M', 'MÓVEL'), ('F', 'FIXO')], max_length=1)),
                ('tel_desc', models.CharField(max_length=10)),
                ('rm', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appAluno.aluno')),
            ],
        ),
    ]
