# Generated by Django 4.2.3 on 2023-10-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAluno', '0006_aluno_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(choices=[('CN', 'Certidão de Nascimento'), ('RGA', 'RG - Aluno'), ('CPFA', 'CPF - Aluno'), ('CV', 'Carteira Vacinação'), ('RGR', 'RG - Responsável'), ('CPFR', 'CPF - Responsável'), ('CNH', 'CNH'), ('FM', 'Ficha de Matrícula'), ('CR', 'Comprovante de Residência'), ('LD', 'Laudo'), ('OT', 'Outros')], default='', max_length=4)),
                ('caminho', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(choices=[('M', 'MÃE'), ('P', 'PAI'), ('T', 'TIA/TIO'), ('I', 'IRMÃ/IRMÃO'), ('A', 'AVÓ/AVÔ'), ('R', 'RESPONSÁVEL'), ('O', 'OUTRO')], max_length=1)),
                ('numero', models.CharField(max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appAluno.aluno')),
            ],
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='Telefones',
        ),
    ]
